<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Create tables for badge assertions and classes
 */
class Version20140713191349 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE networkteam_openbadges_domain_model_badgeassertion (persistence_object_identifier VARCHAR(40) NOT NULL, badgeclass VARCHAR(40) DEFAULT NULL, recipientemailhash VARCHAR(255) NOT NULL, issuedon DATETIME NOT NULL, INDEX IDX_16CFB0591460859D (badgeclass), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE networkteam_openbadges_domain_model_badgeclass (persistence_object_identifier VARCHAR(40) NOT NULL, image VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, criteria VARCHAR(255) NOT NULL, issueridentifier VARCHAR(255) NOT NULL, tags LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', assertionsteps LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', INDEX IDX_FA882285C53D045F (image), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE networkteam_openbadges_domain_model_badgeassertion ADD CONSTRAINT FK_16CFB0591460859D FOREIGN KEY (badgeclass) REFERENCES networkteam_openbadges_domain_model_badgeclass (persistence_object_identifier)");
		$this->addSql("ALTER TABLE networkteam_openbadges_domain_model_badgeclass ADD CONSTRAINT FK_FA882285C53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE networkteam_openbadges_domain_model_badgeassertion DROP FOREIGN KEY FK_16CFB0591460859D");
		$this->addSql("DROP TABLE networkteam_openbadges_domain_model_badgeassertion");
		$this->addSql("DROP TABLE networkteam_openbadges_domain_model_badgeclass");
	}
}